version: "3"

services:
  influxdb:
    image: influxdb:2.1.1
    volumes:
      - ./influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

  telegraf:
    image: telegraf:1.19
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana-oss:8.4.3
    user: "1000:1000" # Ajout de l'utilisateur et du groupe
    volumes:
      - ./grafana-storage:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000
  
  node_red:
    image: nodered/node-red:3.1
    user: "1000:1000" # Ajout de l'utilisateur et du groupe
    volumes:
      - ./node_red:/data:rw
    ports:  
      - ${DOCKER_NODERED_INIT_PORT}:1880

volumes:
  grafana-storage:
  influxdb-storage:
